export { default as HelloWorld } from './HelloWorld'
export { default as PageNotFound } from './PageNotFound'
export { default as Login } from './Cooperado/Login'
export { default as CadastroCoop } from './Cooperado/Cadastro'
export { default as CadastroAdmin } from './Administrador/Cadastro'